name: jetpack
version: 3.0.0-rc1
category: Web
author: NoRedink
maintainer: example@example.com
copyright: 2017 NoRedink
license: BSD3
github: noredink/jetpack
extra-source-files:
- README.md
data-files:
- resources/hmr.js
default-extensions:
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- NamedFieldPuns
- OverloadedStrings
- PackageImports
dependencies:
- file-embed == 0.0.11
- websockets == 0.12.5.3
- concurrent-output == 1.10.9
- lens == 4.17.1
- Glob == 0.9.3
- MissingH == 1.4.1.0
- aeson == 1.4.2.0
- base >= 4.7 && < 5
- bytestring == 0.10.8.2
- clock == 0.7.2
- containers == 0.6.0.1
- directory == 1.3.3.0
- filepath == 1.4.2.1
- formatting == 6.3.7
- fsnotify == 0.3.0.1
- lifted-async == 0.10.0.4
- mtl == 2.2.2
- optparse-applicative == 0.14.3.0
- parsec == 3.1.13.0
- process == 1.6.5.0
- rainbow == 0.30.0.2
- regex-compat == 0.95.1
- safe == 0.3.17
- safe-exceptions == 0.1.7.0
- semver == 0.3.4
- terminal-size == 0.3.2.1
- text == 1.2.3.1
- time == 1.8.0.2
- transformers == 0.5.6.2
- unix == 2.7.2.2
library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-name-shadowing
  other-modules:
  - Paths_jetpack
  - Utils.Files
  - Utils.Parser
  - Utils.Text
  - Utils.Tree
executables:
  jetpack:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jetpack
tests:
  jetpack-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest == 0.16.0.1
    - jetpack
    - tasty == 1.2
    - tasty-hunit == 0.10.0.1
    - tasty-quickcheck == 0.10.1
