name: jetpack
version: 2.0.18
category: Web
author: NoRedink
maintainer: example@example.com
copyright: 2017 NoRedink
license: BSD3
github: noredink/jetpack
extra-source-files:
- README.md
default-extensions:
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- NamedFieldPuns
- OverloadedStrings
- PackageImports
dependencies:
- Glob == 0.9.2
- MissingH == 1.4.0.1
- aeson == 1.2.4.0
- ascii-progress == 0.3.3.0
- base >= 4.7 && < 5
- bytestring == 0.10.8.2
- clock == 0.7.2
- containers == 0.5.10.2
- directory == 1.3.0.2
- filepath == 1.4.1.2
- formatting == 6.3.2
- fsnotify == 0.2.1.1
- lifted-async == 0.9.3.3
- mtl == 2.2.2
- optparse-applicative == 0.14.2.0
- parsec == 3.1.13.0
- process == 1.6.1.0
- rainbow == 0.28.0.4
- regex-compat == 0.95.1
- safe == 0.3.17
- semver == 0.3.3.1
- terminal-size == 0.3.2.1
- text == 1.2.3.0
- time == 1.8.0.2
- transformers == 0.5.2.0
- unix == 2.7.2.2
library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-name-shadowing
  other-modules:
  - Paths_jetpack
  - Utils.Files
  - Utils.Parser
  - Utils.Text
  - Utils.Tree
executables:
  jetpack:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jetpack
tests:
  jetpack-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest == 0.11.4
    - jetpack
    - tasty == 0.11.2.5
    - tasty-hunit == 0.9.2
    - tasty-quickcheck == 0.8.4
