name: jetpack
version: 0.5.3
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/jetpack
extra-source-files:
- README.md
dependencies:
- base >= 4.7 && < 5
- aeson == 1.0.2.1
- text == 1.2.2.1
- filepath == 1.4.1.1
- containers == 0.5.7.1
- transformers == 0.5.2.0
- mtl == 2.2.1
- directory == 1.3.0.0
- parsec == 3.1.11
- free == 4.12.4
- filepath == 1.4.1.1
- Glob == 0.7.*
- process == 1.4.3.0
- MissingH == 1.4.0.1
- lifted-async == 0.9.1.1
- unix == 2.7.2.1
- time == 1.6.0.1
- bytestring == 0.10.8.1
- safe == 0.3.14
- ascii-progress == 0.3.3.0
- regex-compat == 0.95.1
- optparse-applicative == 0.13.1.0
- rainbow == 0.28.0.4
- questioner == 0.1.1.0
- terminal-size == 0.3.2.1
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  other-modules:
  - Utils.Files
  - Utils.Free
  - Utils.Parser
  - Utils.Text
  - Utils.Tree
  - Paths_jetpack
executables:
  jetpack:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jetpack
tests:
  jetpack-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest == 0.11.1
    - jetpack
    - tasty == 0.11.2
    - tasty-hunit == 0.9.2
    - tasty-quickcheck == 0.8.4
